modLoader="javafml"
loaderVersion="[32,)"
license="See GitHub repository for details"
logoFile="logo.png"

[[mods]]
modId="tuckedin"
version="${version}"
displayName="Tucked In"
authors="superckl"
description="Expands the range at which you can sleep in a bed."

[[dependencies.prayers]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.prayers]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"
